logging:
  level:
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: INFO
#    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    ShardingSphere-SQL: WARN
#    org.springframework.orm.jpa: DEBUG
    com.zaxxer.hikari: WARN
    org.springframework.jdbc.core.JdbcTemplate: WARN
    demo.execute: INFO


spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: username
    password: password
    hikari:
      pool-name: execute-hikari-pool-1
      maximum-pool-size: 50

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC

execute:
  sharding:
    enabled: true
    yaml-file-path: sharding/sharding-jdbc-oracle.yml
    database-node-name: sharding0

server:
  port: 9892
