logging:
  level:
    shardingjdbc4: INFO
    shardingjdbc4.config.sharding: DEBUG
    shardingjdbc4.config.filter: DEBUG
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    ShardingSphere-SQL: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.apache.shardingsphere.core.config.log: DEBUG

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/xe
    username: csdpowner
    password: csdpowner
    hikari:
      pool-name: hint-hikari-pool-1
      maximum-pool-size: 10

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.jdbc.time_zone: UTC

hint:
  sharding:
    enabled: true
    yaml-file-path: sharding/sharding-jdbc-oracle.yml
    database-node-name: sharding0

server:
  port: 9891
