-- sharing tables: cities_0, cities_1
create table cities
(
    id               number generated by default on null as identity not null,
    name             varchar2(255 char) default '',
    country          varchar2(255 char) default '',
    population       number             default -1,
    scale            varchar2(255 byte) default '',
    established_time timestamp          default null,
    existed          number(1, 0)       default 1,
    created_time     timestamp                                       not null,
    updated_time     timestamp                                       not null,
    primary key (id)
);
/
create or replace editionable trigger cities_i_trg
    before insert
    on cities
    for each row
begin
    :new.created_time := sys_extract_utc(systimestamp);
end;
/
create or replace editionable trigger cities_iu_trg
    before insert or update
    on cities
    for each row
begin
    :new.updated_time := sys_extract_utc(systimestamp);
end;
/

