create table events
(
    id             number(19, 0) generated by default on null as identity not null,
    category       varchar2(255 char),
    completed_time timestamp(6),
    deleted        number(1, 0),
    name           varchar2(255 char),
    created_time   timestamp,
    updated_time   timestamp,
    primary key (id)
);
/

create or replace editionable trigger events_i_trg
    before insert
    on events
    for each row
begin
    :new.created_time := sys_extract_utc(systimestamp);
end;
/
create or replace editionable trigger events_iu_trg
    before insert or update
    on events
    for each row
begin
    :new.updated_time := sys_extract_utc(systimestamp);
end;
/
create or replace public synonym events for events;
