create table animals
(
    id          number(19, 0) generated by default on null as identity not null,
    scale     number(10, 0),
    record_date date,
    extinct     number(1, 0),
    name        varchar2(255 char),
    created_time   timestamp                                              not null,
    updated_time   timestamp                                              not null,
    primary key (id)
);
/
create or replace editionable trigger animals_i_trg
    before insert
    on animals
    for each row
begin
    :new.created_time := sys_extract_utc(systimestamp);
end;
/
create or replace editionable trigger animals_iu_trg
    before insert or update
    on animals
    for each row
begin
    :new.updated_time := sys_extract_utc(systimestamp);
end;
/
create or replace public synonym animals for animals;
