java:
  sharding:
    datasource:
      master:
        enabled: true
        name: master
        url: jdbc:mysql://localhost:3306/sharding0?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        driver-class-name: org.mariadb.jdbc.Driver
        username: quinn
        password: quinn
      salve1:
        enabled: true
        name: salve1
        url: jdbc:mysql://localhost:3306/sharding1?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        driver-class-name: org.mariadb.jdbc.Driver
        username: quinn
        password: quinn
      salve2:
        enabled: false
        name: salve2
        url: jdbc:mysql://localhost:3306/sharding1?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        driver-class-name: org.mariadb.jdbc.Driver
        username: quinn
        password: quinn


